dist: trusty
language: python
python:
    - 3.8

install:
    # A newer virtualenv is required by whlsetup.sh to use the --no-download option
    - pip install -U virtualenv
    - bash helpers/whldownload.sh -w py -w py${TRAVIS_PYTHON_VERSION//./} -w py${TRAVIS_PYTHON_VERSION//./}-extra
    - mkdir -p /tmp/opt/openquake


script:
    - bash helpers/whlsetup.sh -${TRAVIS_PYTHON_VERSION%.*} -c -s py -s py${TRAVIS_PYTHON_VERSION//./} -s py${TRAVIS_PYTHON_VERSION//./}-extra -d /tmp/opt/openquake
    - python${TRAVIS_PYTHON_VERSION} -c 'from openquake.libs import __version__; print(__version__)'
